# Site settings
title: Shingo Obata
email: s.obata5632@gmail.com
url: https://shingobt.github.io/shingoPortfolio/
description: "GISer and RSer making apps using Django, Flask, R, and Google Apps Engine."
keywords: "Forest management, Remote sensing, Spatial analysis, Forest inventory"
skills: "PhD in Forestry and Natural Resources/Forest Management/Forest Inventory/Spatial Analysis/Remote Sensing/Machine Learning"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Shingo Obata

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ebbe20 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Shingo Obata
  location: Location
  social: Around the Web
  credits: Shingo Obata

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: researchgate
    url: https://www.researchgate.net/profile/Shingo_Obata
  - title: twitter
    url: http://twitter.com/ShingObt
  - title: facebook
    url: https://m.facebook.com/taba.gonsi
  - title: linkedin
    url: https://www.linkedin.com/in/shingo-obata-b48a25106/
  - title: github
    url: https://github.com/ShingObt


# Postal address (add as many lines as necessary)
address:
  - line: the National Institute for Mathematical and Biological Synthesis
  - line: Knoxville, Tennessee, United States

# Credits content
credits: 'This page is based on <a href="http://startbootstrap.com">Freelancer</a> theme in Jekyll.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
